def letterToNumber(s):
    num_list = []
    for c in s:
        num_list.append(str((ord(c) - 65)))
    return num_list


cipherInput ="IYEGXPXMMOETTNZKAYAUYYTTBBMVFFYYKKKCIGXELZFXBAVSIJZOXQBBNXUWIOYZVTFRVABXMZXWYROXAZRTXOEOLSKUTJAEKMGWABWHVAMYKPHQVCQLFMQNWOEOBRMETXOFVTQMGHJIIGIRWTKEVYQVFIFAJAEKMGWALYYVAVMUCKIYJQHLNHGGZZWGQBUTXGIMFYLRYVUDAVPIGVL"
cipherText = letterToNumber(cipherInput)

key = [0] * 10

